title: Hackney Systems Mapping
baseurl: /hackney-data-flows
exclude:
- generate.rb
- Gemfile
- Gemfile.lock
- .gitignore
system_mapping:
  enabled: true
  system_maps:
  - apis
  - services
plugins:
- jekyll-diagrams
diagrams:
  graphviz:
    engine: dot
    options: '-Tsvg'
  diag:
    options: '-Tsvg --nodoctype'